services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    volumes:
      - mongodb_data:/data/db

  graphql-server:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/timelines?authSource=admin
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - graphql-server

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped

volumes:
  mongodb_data:
