services:
  graphql-server:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/timelines?authSource=admin&replicaSet=rs0
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
    depends_on:
      - mongodb-init

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - graphql-server

  mongodb:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/keyfile/mongo-keyfile"]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    volumes:
      - mongodb_data:/data/db
      - mongodb_keyfile:/data/keyfile
    user: "999:999"
    healthcheck:
      test: mongosh --username ${MONGODB_USER} --password ${MONGODB_PASS} --authenticationDatabase admin --eval "db.adminCommand('ping')" --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb-init:
    image: mongo:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    volumes:
      - ./mongodb/init-replica-set.sh:/init-replica-set.sh:ro
      - mongodb_keyfile:/data/keyfile
    entrypoint: ["/bin/bash", "/init-replica-set.sh"]
    restart: on-failure

  event-processor:
    build:
      context: ./backend
    command: npm run processor
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/timelines?authSource=admin&replicaSet=rs0
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
    depends_on:
      - mongodb-init
      - graphql-server

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    ports:
      - "8123:8123"
    volumes:
      - ./.config:/config
    environment:
      - TZ=Europe/Vienna
    restart: unless-stopped

volumes:
  mongodb_data:
  mongodb_keyfile:
