version: "3"
services:
  timelines-backend:
    image: ghcr.io/mloitzl/timelines-backend:latest
    ports:
      - "4000:4000"
    environment:
      # - MONGODB_URI=mongodb://mongodb:27017/timelines?authSource=admin
      # - MONGODB_USER=${MONGODB_USER}
      # - MONGODB_PASS=${MONGODB_PASS}
    depends_on:
      - mongodb
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_REGISTRY_AUTH=true
      - WATCHTOWER_NOTIFICATION_REPORT=false
      - REGISTRY_AUTH_FILE=/config/config.json
      - GHCR_USERNAME=${GITHUB_USER}
      - GHCR_TOKEN=${GHCR_GITHUB_PAT}
    restart: unless-stopped
volumes:
  mongodb_data:
