name: Backend CI

on:
    push:
        branches: [main]
        paths:
            - "backend/**"
            - "mongodb/**"
            - ".github/workflows/backend.yml"
    pull_request:
        branches: [main]
        paths:
            - "backend/**"
            - "mongodb/**"
            - ".github/workflows/backend.yml"

jobs:
    build:
        runs-on: self-hosted

        services:
            mongodb:
                image: mongo:latest
                ports:
                    - 57017:27017

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: backend/package-lock.json

            - name: Install dependencies
              working-directory: backend
              run: npm ci

            - name: Build
              working-directory: backend
              run: npm run build

            - name: Build Docker image
              working-directory: backend
              run: |
                docker build -t timelines-backend .

    # Optionally add container publishing to GitHub Container Registry
    publish:
        needs: build
        runs-on: self-hosted
        if: github.ref == 'refs/heads/main' # Only publish on main branch pushes

        steps:
            - uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_PAT }}

            - name: Build and push backend Docker image
              uses: docker/build-push-action@v4
              with:
                  context: ./backend
                  target: backend
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/timelines-backend:latest
                      ghcr.io/${{ github.repository_owner }}/timelines-backend:${{ github.sha }}


            - name: Build and push mongodb-init Docker image
              uses: docker/build-push-action@v4
              with:
                  context: ./mongodb
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/timelines-mongodb-init:latest
                      ghcr.io/${{ github.repository_owner }}/timelines-mongodb-init:${{ github.sha }}
