name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/schema.graphql"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - "backend/schema.graphql"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Sync GraphQL schema
        run: cp backend/schema.graphql frontend/schema.graphql

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/timelines-frontend:latest
            ghcr.io/${{ github.repository_owner }}/timelines-frontend:${{ github.sha }}
          build-args: |
            VITE_API_URL=http://werkstatt:4000/graphql
            VITE_WS_URL=ws://werkstatt:4000/graphql
